### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by mistycheney** [leoxiaobin/deep-high-resolution-net.pytorch#10]
Thanks for sharing the code. When I tried to run the test commands both failed with 
`cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor`. Am I missing something? Thanks,

**Comment by mistycheney** [comment]
Never mind. This is because the images have not been downloaded.

**Comment by mistycheney** [comment]
After I downloaded the mpii images and place them according to the required location, the mpii command still fails with `cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor`.

**Comment by zharthur** [comment]
Hello, I'm also met this problem. Because this dataset is so big, if you download it and put it in the image, does that error go away?
Thank you!

**Comment by JisuiWang** [comment]
@zharthur Of course. Most of this error in opencv occurs because the address of the picture is empty.

**Comment by zharthur** [comment]
> @zharthur Of course. Most of this error in opencv occurs because the address of the picture is empty.
That's true. Thank you very much. And I want to get a visual result, do you know any visual demos? 
Thank you again.

**Comment by zharthur** [comment]
> @zharthur Of course. Most of this error in opencv occurs because the address of the picture is empty.

That's true. Thank you very much. And I want to get a visual result, do you know any visual demos? 
Thank you again.
