### ISSUE TITLE
Tensor size mismatch

### ISSUE THREAD

**Issue by DannyYCCheng** [leoxiaobin/deep-high-resolution-net.pytorch#110]
I am trying to train using a set of custom images, and basing my configuration file on w48_384x288_adam_lr1e-3.yaml. The only thing I have changed is NUM_JOINTS from 17 to 24, and I get the following error:

> RuntimeError: The size of tensor a (6912) must match the size of tensor b (4896) at non-singleton dimension 1

Do I need to change other parameters too?

**Comment by Masum06** [comment]
Hi, it's been a while, but did you get to solve the issue?
