### ISSUE TITLE
How to test on test-dev dataset?

### ISSUE THREAD

**Issue by yuechengyu0710** [leoxiaobin/deep-high-resolution-net.pytorch#114]
If I want to test on the test-dev dataset, what should I do? Thanks

**Comment by gaoyao123** [comment]
First,you should pack your results in your computer.Then you can upload them to the server.You can learn more information from this address:http://cocodataset.org/#keypoints-2019.

**Comment by yuechengyu0710** [comment]
> First,you should pack your results in your computer.Then you can upload them to the server.You can learn more information from this address:http://cocodataset.org/#keypoints-2019.

thanks
