### ISSUE TITLE
cv2.error  opencv

### ISSUE THREAD

**Issue by angechen** [leoxiaobin/deep-high-resolution-net.pytorch#123]
When I train on COCO train2017 dataset:
    python tools/train.py \
    --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml \
It occurs this error:
![图片](https://user-images.githubusercontent.com/45162172/66715014-c08e5c80-edf0-11e9-9e86-87c907b85d7b.png)
I don't know if  it is because the version of opencv-python，or it has nothing to do with the version of opencv-python.
I pip install opencv-python==3.4.2.17. I had tried to pip install opencv-python==4.1.1 It occurs the following error:
![图片](https://user-images.githubusercontent.com/45162172/66715025-e9aeed00-edf0-11e9-93ee-a1dcad6377d6.png)

**Comment by GongXinyuu** [comment]
hello, have you solve this issue? @angechen

**Comment by PedroPPMN** [comment]
Hello, I'm having the exacly same problem. Could you tell me how you solved it, please?

**Comment by Aliiiu** [comment]
pls share if you were able to solve this

**Comment by karamjotsinghmalik** [comment]
Dataset directory structure should be as mentioned in : 
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch#data-preparation

The error originates from dataloader, when image files can't be found.
