### ISSUE TITLE
How to test on my own data?

### ISSUE THREAD

**Issue by xiaochehe** [leoxiaobin/deep-high-resolution-net.pytorch#126]
I want to use your code for pose estimation, but I realize person detection is needed in the first stage. And I discover that you have provided the detection results for coco dataset. How can I generate it for my own dataset? Could you provide some advices or codes?

**Comment by eng100200** [comment]
@xiaochehe hello, you need to use a big model like RCNN or YOLO V3 for detection of your own dataset, and then save the detection results in the same format as provided by this code for coco dataset. And then the rest is to perfrom pose estimation.
