### ISSUE TITLE
How to prapare COCO test-dev2017 and get the test results on COCO test-dev 2017 as the table in paper?

### ISSUE THREAD

**Issue by banana16314** [leoxiaobin/deep-high-resolution-net.pytorch#130]
Thanks for your great work!
I trained the model on COCO train2017 and got the results on COCO val2017. Now i wanna get the test results on COCO test-dev2017. What shall i do to prepare the test-dev data and to test the retrained model? 

I found dataset 2017 Test images and 2017 Testing image info in http://cocodataset.org/#download, however, i did not get the keypoint info from 2017 tesinging image info zip.

**Comment by banana16314** [comment]
done! 
first, we  download the test2017 dataset and image info.
second, we download the detection result on test-dev2017. # 4 there is a link.
third, we test on the test-dev2017 and submit the json to coco keypoint challenge.
finally, we can get the ap scores from coco's feedback.

**Comment by trqminh** [comment]
@banana16314 , can I ask where you submit the evaluation? Thank you.
