### ISSUE TITLE
There is a AP value after each epoch. Is it the AP value on val2017?

### ISSUE THREAD

**Issue by banana16314** [leoxiaobin/deep-high-resolution-net.pytorch#132]
Can the AP value after each epoch be used in the Table of Results on COCO val2017 with detector having human AP of 56.4 on COCO val2017 dataset in the README?

**Comment by leoxiaobin** [comment]
If you do not change the training config file, the AP value after each epoch is an  AP using the ground truth person bbox. The AP is not comparable with the AP used in the Table of Results. The AP in the Table is obtained by using bbox from a person detector having person AP of 56.4.
