### ISSUE TITLE
The HRnet is slower in Windows Pytorch

### ISSUE THREAD

**Issue by Ben-Park** [leoxiaobin/deep-high-resolution-net.pytorch#137]
Hello, i try to run HRNet in Windows Pytorch. The problem is inference time is almost double in Windows Pytorch.  My condition is like below.

- I just measure a time just before and after forwarding.
- Same code is used in Linux and Windows.
- Pytorch 1.0 is very slow in Windows, so I use Pytorch0.4.0. then the problem is a little bit alleviate but still very slow.
- When i check GPU status in Windows, a GPU is working.

Anybody has an idea to deal with the problem??

**Comment by leoxiaobin** [comment]
We do not fully test our code in Windows. I suggest you using the code in Linux. The code is fully tested in Linux.

**Comment by Ben-Park** [comment]
Yeb. That is the best way to test the code.

 

For someone want to test in Windows, PyTorch 0.4.0. is a proper choice rather than PyTorch 1.0. The speed of inference is Linux > PyTorch 0.4.0 > PyTorch 1.0.

**Comment by AIprogrammer** [comment]
Hi, while doing inference on COCO datatset with the setting (model : hrnet-w32-256-192, batch size of 256, 4 1080Ti gpus), how much time would be reasonable?
