### ISSUE TITLE
I test the model on MPII

### ISSUE THREAD

**Issue by henbucuoshanghai** [leoxiaobin/deep-high-resolution-net.pytorch#145]
File "tools/test.py", line 131, in <module>
    main()
  File "tools/test.py", line 99, in main
    model = torch.nn.DataParallel(model, device_ids=cfg.GPUS).cuda()

lib/python3.6/site-packages/torch/cuda/__init__.py", line 318, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

**Comment by henbucuoshanghai** [comment]
I have to have 4 gpus ????????????

**Comment by henbucuoshanghai** [comment]
GPUS: (0,1,2,3)??????????????

**Comment by Nghingtim** [comment]
Dear Hen,

I met the same problem, like this:   "raise AssertionError("Invalid device id") AssertionError: Invalid device id"

I want to make sure that only we have 4 GPU, could we run the test.py successfully?

**Comment by hyunjerry** [comment]
> Dear Hen,
> 
> I met the same problem, like this: "raise AssertionError("Invalid device id") AssertionError: Invalid device id"
> 
> I want to make sure that only we have 4 GPU, could we run the test.py successfully?

Hello Nghingtim,

You can rest test.py with one GPU.

Please check the link below for your error :) 

https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/27#issuecomment-477504563
