### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ly5234** [leoxiaobin/deep-high-resolution-net.pytorch#150]
when I try to train by 'python tools/train.py  --cfg experiments/mpii/hrnet/w32_256x256_adam_lr1e-3.yaml' 
some errors occurred：

=> init weights from normal distribution
=> loading pretrained model models/pytorch/imagenet/hrnet_w32-36af842e.pth
Illegal instruction (core dumped)

Maybe someone know why? Can you help me, thanks.

**Comment by leoxiaobin** [comment]
Can you run pytorch correctly? Which pytorch version are you using?

**Comment by ly5234** [comment]
@leoxiaobin Thanks for your reply. 
Although I'm not entirely sure if it is due to the library version, I retry to run the project in a new environment with python 3.6 + pytorch1.1.0, it works well. May reinstall the correct version of some libraries will solve this problem.
