### ISSUE TITLE
nvidia-docker is deprecated.

### ISSUE THREAD

**Issue by sklationd** [leoxiaobin/deep-high-resolution-net.pytorch#168]
readme of demo said, we can run container by nvidia-docker, but latest version of docker does not support `nvidia-docker` command.

we can use 
```
docker run --gpus all --rm -it \
    -v $(pwd)/output:/output \
    -v $(pwd)/videos:/videos \
    -v $(pwd)/models:/models \
    -w /pose_root \
    hrnet_demo_inference \
    /bin/bash
```
instead of `nvidia-docker`

**Comment by rangerToby** [comment]
Hi，sklationd. can you run the demo successfully as readme said?

**Comment by sklationd** [comment]
> Hi，sklationd. can you run the demo successfully as readme said?

Yes, I followed every command in readme except for nvidia-docker command only.
Make sure you build your dockerfile with ./builder-docker.sh

**Comment by rangerToby** [comment]
thanks, but  i found there is not nvidia driver in the docker images, it's strange~

**Comment by sklationd** [comment]
You should install nvidia-docker.
https://github.com/NVIDIA/nvidia-docker

**Comment by rangerToby** [comment]
thanks~finally, i run a part of the demo code in another docker env
