### ISSUE TITLE
Usage on CPU

### ISSUE THREAD

**Issue by zhj123169** [leoxiaobin/deep-high-resolution-net.pytorch#17]
Currently when trying to make libs on my pc(without gpu),I get the following error:
![QQ图片20190314194347](https://user-images.githubusercontent.com/28223576/54354429-8f4e8200-4691-11e9-8e42-cb94fa522dab.png)
Could you give me some suggestions of it？Thank you！

**Comment by tengshaofeng** [comment]
@zhj123169 ,hi , I met the same error in mac os.
Have u solved it ?

**Comment by tengshaofeng** [comment]
em, i solved it by comment some lines in setup_linux.py

**Comment by ankitksharma** [comment]
@tengshaofeng Can you share the commented setup_lunux.py file?
