### ISSUE TITLE
How Can I Get The Pretrained Weights

### ISSUE THREAD

**Issue by JiangWeiHn** [leoxiaobin/deep-high-resolution-net.pytorch#171]
I am in china and cannot open OneDrive or GoogleDrive ,please tell me how can i get the pretrained pth file?  Can you upload the file to Baidu cloud disk？thanks a lot

**Comment by leoxiaobin** [comment]
OneDrive URLs should be able to be opened in China. Can't you still open it?

**Comment by JiangWeiHn** [comment]
我通过翻墙软件得到

**Comment by Jackxiong863** [comment]
> 我通过翻墙软件得到

你好，请问能否通过百度网盘分享下demo里面的pretrained模型，我也不会翻墙。

**Comment by WZMIAOMIAO** [comment]
链接:https://pan.baidu.com/s/1Lu6mMAWfm_8GGykttFMpVw 提取码:f43o

**Comment by JiangWeiHn** [comment]
thanks  a lot
