### ISSUE TITLE
Fps error while running inference.py

### ISSUE THREAD

**Issue by danial880** [leoxiaobin/deep-high-resolution-net.pytorch#172]
I have used the following command to run inference.py

 python inference.py   --cfg inference-config.yaml   --videoFile /videos/video.mp4   --inferenceFps 10   --writeBoxFrames   TEST.MODEL_FILE   models/pytorch/pose_coco/pose_hrnet_w32_384x288.pth

Here are the logs

******************************************************************
=> loading model from models/pytorch/pose_coco/pose_hrnet_w32_384x288.pth
desired inference fps is 10 but video fps is 0.0
******************************************************************

**Comment by gachiemchiep** [comment]
@danial880 
Your video is failed to load, check the path of your video 

    vidcap = cv2.VideoCapture(args.videoFile)
    fps = vidcap.get(cv2.CAP_PROP_FPS)
    if fps < args.inferenceFps:
        print('desired inference fps is '+str(args.inferenceFps)+' but video fps is '+str(fps))
        exit()
