### ISSUE TITLE
Questions about the transition layers between stages in the codes

### ISSUE THREAD

**Issue by prophett0527** [leoxiaobin/deep-high-resolution-net.pytorch#180]
Hello, 
I have some questions about the transition layers between stages in PoseHighResolutionNet class.

The transition layers contains conv3x3 layers with stride=1 and stride=2.
The codes seem similar with the fusion layers in HighResolutionModule class.
Fusion layers have conv1x1 layers for upsampling, but transition layers do not have conv1x1.
What is the difference between these two type layers?
What happens if there are no transition layers between stages?

I couldn't find any explanations about transition layers in the original paper.
Could you please kindly explain the transition layers here?
Thank you!

**Comment by aFewThings** [comment]
Hi, have you found your answer?
