### ISSUE TITLE
How to use the MPII test.json(7000+ samples)  to generate the "pred.mat" ?

### ISSUE THREAD

**Issue by PCRKTY** [leoxiaobin/deep-high-resolution-net.pytorch#219]
How to use the MPII test.json(7000+ samples)  to generate the "pred.mat" which is needed to evaluate the PCKh score?

**Comment by Aliiiu** [comment]
pls I can see you closed this, pls share how you were able to solve this

**Comment by cv-boss** [comment]
pls share how you were able to solve this

**Comment by Aliiiu** [comment]
> pls share how you were able to solve this

i wasn't able to solve it
