### ISSUE TITLE
How to find feature is not aligned.

### ISSUE THREAD

**Issue by HuAndrew** [leoxiaobin/deep-high-resolution-net.pytorch#22]
@leoxiaobin  Thanks for sharing your work. 

Could you please explain how to find **feature is not aligned**.

 [SHIFT_HEATMAP operation in function.py](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/master/lib/core/function.py#L143-L146)
```python
# feature is not aligned, shift flipped heatmap for higher accuracy
if config.TEST.SHIFT_HEATMAP:
    output_flipped[:, :, :, 2:] = \
        output_flipped.clone()[:, :, :, 0:-2]
```

Test coco valid dataset in w32_256x192 model (gt bbox) , and results as follow:

| Arch | AP | Ap .5 | AP .75 | AP (M) | AP (L) | AR | AR .5 | AR .75 | AR (M) | AR (L) |
|---|---|---|---|---|---|---|---|---|---|---|
| NOT SHIFT_HEATMAP| **0.720** | 0.932 | 0.802 | 0.692 | 0.771 | 0.774 | 0.946 | 0.850 | 0.736 | 0.832 |
| SHIFT_HEATMAP 1 pixel| **0.740** | 0.932 | 0.815 | 0.717 | 0.780 | 0.791 | 0.947 | 0.857 | 0.760 | 0.839 |
| SHIFT_HEATMAP 2 pixel| **0.674** | 0.928 | 0.779 | 0.661 | 0.703 | 0.738 | 0.942 | 0.830 | 0.713 | 0.775 |

Thank you so much!

**Comment by HuAndrew** [comment]
I get it, thank your work!

**Comment by 3colorsDog** [comment]
> I get it, thank your work!

Hi, HuAndrew. I still don't understand, could you please tell me why?
