### ISSUE TITLE
Cant reproduct the 90.3 result on MPII

### ISSUE THREAD

**Issue by mobeixiaoxin** [leoxiaobin/deep-high-resolution-net.pytorch#235]
when i training on MPII dataset, i can only get 90.1 result on the valid,
Does anyone who can reproduct the result 90.3? if so, can you tell me you config??
Thanks very much

**Comment by 15023520700** [comment]
May I ask if you have solved this problem? I trained on mpii data set and tested on val with the highest accuracy of only 89.9

**Comment by ll8657** [comment]
> when i training on MPII dataset, i can only get 90.1 result on the valid, Does anyone who can reproduct the result 90.3? if so, can you tell me you config?? Thanks very much

May I ask if you have solved this problem? I trained on mpii data set and tested on val with the highest accuracy of only 89.9
