### ISSUE TITLE
ModuleNotFoundError: No module named 'nms.cpu_nms'

### ISSUE THREAD

**Issue by tianjiahao** [leoxiaobin/deep-high-resolution-net.pytorch#24]
myubuntu@myubuntu-Precision-WorkStation-T5500:~/Desktop/deep-high-resolution-net.pytorch-master$ python tools/test.py \ --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml \ TEST.MODEL_FILE models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth \ TEST.USE_GT_BBOX False
Traceback (most recent call last):
  File "tools/test.py", line 31, in <module>
    import dataset
  File "/home/myubuntu/Desktop/deep-high-resolution-net.pytorch-master/tools/../lib/dataset/__init__.py", line 12, in <module>
    from .coco import COCODataset as coco
  File "/home/myubuntu/Desktop/deep-high-resolution-net.pytorch-master/tools/../lib/dataset/coco.py", line 22, in <module>
    from nms.nms import oks_nms
  File "/home/myubuntu/Desktop/deep-high-resolution-net.pytorch-master/tools/../lib/nms/nms.py", line 13, in <module>
    from .cpu_nms import cpu_nms
ModuleNotFoundError: No module named 'nms.cpu_nms'

**Comment by ankitgc1** [comment]
go to lib directory and run make

**Comment by Smoothing97** [comment]
> myubuntu@myubuntu-Precision-WorkStation-T5500:~/Desktop/deep-high-resolution-net.pytorch-master$ python tools/test.py \ --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml \ TEST.MODEL_FILE models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth \ TEST.USE_GT_BBOX False
> Traceback (most recent call last):
> File "tools/test.py", line 31, in 
> import dataset
> File "/home/myubuntu/Desktop/deep-high-resolution-net.pytorch-master/tools/../lib/dataset/**init**.py", line 12, in 
> from .coco import COCODataset as coco
> File "/home/myubuntu/Desktop/deep-high-resolution-net.pytorch-master/tools/../lib/dataset/coco.py", line 22, in 
> from nms.nms import oks_nms
> File "/home/myubuntu/Desktop/deep-high-resolution-net.pytorch-master/tools/../lib/nms/nms.py", line 13, in 
> from .cpu_nms import cpu_nms
> ModuleNotFoundError: No module named 'nms.cpu_nms'

sorry but I really wanna know if you have sloution.My file structure is:
![image](https://user-images.githubusercontent.com/32809975/55627929-f3bcb700-57e1-11e9-8234-e8de57b191ab.png)

in nms_wrapper.py,I have:

> `import numpy as np
import torch

> from .gpu_nms import gpu_nms
from .cpu_nms import cpu_nms
from .cpu_soft_nms import cpu_soft_nms`

Error is:

> from .cpu_nms import cpu_nms                                               
> ImportError: cannot import name 'cpu_nms'

really need your help,thx！

**Comment by khan958** [comment]
> go to lib directory and run make

**How can we run a make  file for windows?**? Kindly need your suggestion.

**Comment by henbucuoshanghai** [comment]
go to lib directory and run make      it has this error

**Comment by henbucuoshanghai** [comment]
go to lib directory and run make it has this error

cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 44, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

**Comment by henbucuoshanghai** [comment]
why?????

**Comment by leoxiaobin** [comment]
Have you installed cuda?
If you have already installed cuda, do you add it to your $PATH? You can simply check it by run
```
echo $PATH
```

**Comment by neilctwu** [comment]
I encountered the same error here, here's how I solved:
1. In windows, the exact name of nvcc is `nvcc.exe`, so either change `nvcc` to `nvcc.exe` on L42 or L38 if you added CUDAHOME in environment.
2. `lib64` folders under CUDA directory is `lib\x64\`, in windows, therefore changing L50's relavent variable.
Hoola! OSError is gone!

However you'll get next error showed `AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'`. this seems not solvable in windows right now.

**Comment by sohamvyas73** [comment]
> I encountered the same error here, here's how I solved:
> 
> 1. In windows, the exact name of nvcc is `nvcc.exe`, so either change `nvcc` to `nvcc.exe` on L42 or L38 if you added CUDAHOME in environment.
> 2. `lib64` folders under CUDA directory is `lib\x64\`, in windows, therefore changing L50's relavent variable.
>    Hoola! OSError is gone!
> 
> However you'll get next error showed `AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'`. this seems not solvable in windows right now.

MSVCCompiler is used for linux environment  but here we use windows environment. There are lots of env errors if we use it in windows

**Comment by lhw-hu** [comment]
I couldn' run make,show:(base) F:\code\deeplearning\HRNet\lib>make 
'make' 不是内部或外部命令，也不是可运行的程序或批处理文件。
I work in window10 F:\code\deeplearning\HRNet is my ${POSE_ROOT}
As a beginner, I really do not know how to do, can you give me some help please

**Comment by Jeba-create** [comment]
> go to lib directory and run make

I got the same error as "    from .gpu_nms import gpu_nms
ModuleNotFoundError: No module named 'nms.gpu_nms'"

Can you please help me to solve this? There is a file named "Makefile" within lib, but how to run cmake?

**Comment by liang0502** [comment]
> 
all:
	cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../
clean:
	cd nms; rm *.so; cd ../../


里面内容如上，windows直接运行，问题是会出现上面那个老哥的os错误

**Comment by shfunc** [comment]
import sys
sys.path.append('/path_to/simple-HRNet/misc/nms/')
(simple* because I use another repo)

You can also try this.

**Comment by aubeliang** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
