### ISSUE TITLE
请教代码意思。

### ISSUE THREAD

**Issue by YuQi9797** [leoxiaobin/deep-high-resolution-net.pytorch#241]
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/ba50a82dce412df97f088c572d86d7977753bf74/lib/dataset/mpii.py#L58

作者您好，请问下这里避免裁剪到肢体， 是自己自定义轻微调整center 和 scale的值吗？ 具体表示的是什么意思呢？
纵坐标和尺度发生变化?

**Comment by BangwenHe** [comment]
看这部分代码的含义应该是center向右平移15*s[1]，bbox框扩大到1.25倍，从而多获得一些图片上的信息以获得更好的姿态估计结果。https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/197，这里乘了1.25之后框变大了，大概就是这个原理。

**Comment by leijue222** [comment]
> 看这部分代码的含义应该是center向右平移15*s[1]，bbox框扩大到1.25倍，从而多获得一些图片上的信息以获得更好的姿态估计结果。[这里](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/197)乘了1.25之后框变大了，大概就是这个原理。

https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/ba50a82dce412df97f088c572d86d7977753bf74/lib/dataset/coco.py#L223-L227
请问您知道为什么是放大1.25倍吗？以及为什么self.pixel_std固定设置为200。关于1.25和200这两个trick值的设定该如何解释

**Comment by BangwenHe** [comment]
> > 看这部分代码的含义应该是center向右平移15*s[1]，bbox框扩大到1.25倍，从而多获得一些图片上的信息以获得更好的姿态估计结果。[这里](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/197)乘了1.25之后框变大了，大概就是这个原理。
> 
> https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/ba50a82dce412df97f088c572d86d7977753bf74/lib/dataset/coco.py#L223-L227
> 
> 
> 请问您知道为什么是放大1.25倍吗？以及为什么self.pixel_std固定设置为200。关于1.25和200这两个trick值的设定该如何解释

你好，下面是我个人认为的解释：

- 放大1.25倍就如注释所说的那样，是为了避免裁剪到肢体。这是考虑到一些比较极端的情况，例如四肢全部张开，成一个五角星的样子，这种情况下目标检测器可能不会把所有的肢体都包括进来，所以需要手动扩大一些。至于1.25我认为是一个大家都取的超参数，我[自己的一些代码](https://github.com/BangwenHe/RealsenseDepth/blob/7fdabe298e/hourglass_pose.py#L31)里也会直接取1之类的（虽然最后没用到）。issue里也有很多的讨论：[mmpose](https://mmpose.readthedocs.io/en/latest/faq.html#evaluation), [issues/94](https://github.com/microsoft/human-pose-estimation.pytorch/issues/94#issuecomment-701986720)
- 200只是一个超参数，[前面](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/master/demo/demo.py#L180)缩小了200个像素，[后面](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/master/lib/utils/transforms.py#L65)放大200个像素。所以你应该可以自己修改这个参数，或者直接在这两个地方把这个两个200全删掉。
