### ISSUE TITLE
关于论文的网络结构和实现的网络结构不同

### ISSUE THREAD

**Issue by koumudai** [leoxiaobin/deep-high-resolution-net.pytorch#268]
![1](https://user-images.githubusercontent.com/53834748/140002983-03ea46fa-ae54-438e-98b3-84183a0dfd99.png) 中，从stage3 到stage4 的时候，如下图所示，
![5](https://user-images.githubusercontent.com/53834748/140003097-da54e458-d9ae-42c6-a78c-059cf8916365.PNG)。而实际的网络架构实现为
![7](https://user-images.githubusercontent.com/53834748/140005760-5eadcf1b-b36c-4304-8b40-08a70fa6cb10.PNG)

**Comment by Maybeiscai** [comment]
请问是这样的么，还是我理解错误了

**Comment by unauna9739** [comment]
应该是这样的，然后stage3的模块化块重复4次，stage3到stage4的部分是transition层
