### ISSUE TITLE
how to make this model working in realtime(webcam)

### ISSUE THREAD

**Issue by ankitgc1** [leoxiaobin/deep-high-resolution-net.pytorch#28]

**Comment by YinRui1991** [comment]
You need to have a person detector first, and write a opencv file to combine the detector and hrnet together.

**Comment by stefanopini** [comment]
I'm working for a light and easy-to-use version of HRNet.
You can find my re-implementation here: [**simple-HRNet**](https://github.com/stefanopini/simple-HRNet) (https://github.com/stefanopini/simple-HRNet).

**Comment by oftenliu** [comment]
@stefanopini   do you compress the model?

**Comment by stefanopini** [comment]
@oftenliu No, I didn't.

**Comment by Jichen66** [comment]
> I'm working on a light and easy-to-use version of HRNet.
> You can find my re-implementation here: [simple-HRNet](https://github.com/stefanopini/simple-HRNet) (https://github.com/stefanopini/simple-HRNet).
> 
> Currently, the repo contains a simplified pytorch model that is compatible with official pre-trained weights and a script to run a **multi-person live demo** using YOLOv3 as person detector.

Hi, does it support Windows system?

**Comment by stefanopini** [comment]
@Jichen66 Yes! It supports both Windows and Linux.

**Comment by Jichen66** [comment]
Nice work! And I met a problem during testing and post a issue on your repo. Do you have idea on how to solve it? Many thanks in advance!

**Comment by Jichen66** [comment]
> 
> 
> @Jichen66 Yes! It supports both Windows and Linux.

Nice work! And I met a problem during testing and post a issue on your repo. Do you have idea on how to solve it? Many thanks in advance!

**Comment by Jichen66** [comment]
@stefanopini  Nice work! And I met a problem during testing and post a issue on your repo. Do you have idea on how to solve it? Many thanks in advance!
