### ISSUE TITLE
What size is accepted by the pretrained COCO model?

### ISSUE THREAD

**Issue by fengyang0317** [leoxiaobin/deep-high-resolution-net.pytorch#29]
I want to inference on a 1280x720 image. I got RuntimeError: The size of tensor a (180) must match the size of tensor b (184) at non-singleton dimension 3.

**Comment by fengyang0317** [comment]
multiplier of 32

**Comment by savan77** [comment]
@fengyang0317 Try resizing your image before sending it for inference. For example, if you are using 256x192 model, then you can add a transformation in `transforms.Compose` as follows:

`transform = transforms.Compose([
        transforms.Resize((256,192)),
        transforms.ToTensor(),
        normalize,
    ])`
