### ISSUE TITLE
Have you tried using intermediate supervision?

### ISSUE THREAD

**Issue by 994374821** [leoxiaobin/deep-high-resolution-net.pytorch#32]
Thanks for your works! Have you tried using intermediate supervision? Do you think it would be helpful to include intermediate supervision in the model?

**Comment by JD-Lab** [comment]
@994374821 We have not tried to use the intermediate supervision. It's not clear whether that is useful. You're welcome to provide the implementation of that.
Thanks for your attention.

**Comment by abhiagwl4262** [comment]
@994374821 Hey did you try with intermediate supervision? If Yes, can you share your observations with me ?
