### ISSUE TITLE
Train/Val split

### ISSUE THREAD

**Issue by lg-zhang** [leoxiaobin/deep-high-resolution-net.pytorch#34]
Thanks for making the code available!
Could you explain how you split the data in MPII's "annot"? Is this data split universally agreed or just for this paper?

There are:
22246 individuals in "train.json",
29116 individuals in "trainval.json",
2958 individuals in "valid.json",
7247 individuals in "test.json".

What confuses me is that 22246 + 2958 != 29116. Also trainval.json is not used anywhere.

I'm wondering when we report results (like what you did for Table 3 in your paper), which split should we use for training and testing, respectively?

**Comment by leoxiaobin** [comment]
MPII do not provide the officail train/val split. I followed the split of [tompson_cvpr15](https://cims.nyu.edu/~tompson/others/tompson_cvpr15.pdf)

**Comment by doublemanyu** [comment]
> MPII do not provide the officail train/val split. I followed the split of [tompson_cvpr15](https://cims.nyu.edu/~tompson/others/tompson_cvpr15.pdf). For the table in our repo I used 22246 individuals in "train.json" for training, and 2958 individuals in "valid.json" for evaluation. For Table 3 in our paper, we use all 29116 individuals in "trainval.json" for training, and use 7247 individuals in "test.json" for test.

Hi, there. Thanks for your wonderful work. Can you tell me about the generation of gt_valid.mat? How did you get that? Thank you in advance.
