### ISSUE TITLE
Would it be possible to run this in Windows 10?

### ISSUE THREAD

**Issue by FrancescoPiemontese** [leoxiaobin/deep-high-resolution-net.pytorch#35]

**Comment by leoxiaobin** [comment]
it depends on if pytorch can run in windows. For my knowledge, pytorch can already run in windows, so it is  possible to run this in windows 10. But I do not test it in windows.

**Comment by FrancescoPiemontese** [comment]
Thank you for your answer, I will try

**Comment by BanaBear** [comment]
> Thank you for your answer, I will try

hello, have you succeeded running this model in Win10?

**Comment by FrancescoPiemontese** [comment]
Yes, although it took me a bit. You won't be able to build the libraries in Windows 10, but like @leoxiaobin mentioned, PyTorch fully supports it, so you can import the model configuration and weights and run it yourself, without using the test/train.py files.

**Comment by BanaBear** [comment]
> Yes, although it took me a bit. You won't be able to build the libraries in Windows 10, but like @leoxiaobin mentioned, PyTorch fully supports it, so you can import the model configuration and weights and run it yourself, without using the test/train.py files.

got it, thank you!

**Comment by timtensor** [comment]
@FrancescoPiemontese , i am trying to run the pre trained model , but i am having quite a hard time to configure it to windows.  Did you follow any tutorials as such to configure your setup . If you have could be great if you could share it !

**Comment by FrancescoPiemontese** [comment]
Hi, I didn't follow any tutorial. PyTorch supports Windows 10, so you shouldn't need to make many modifications. The main problem i had is that in Windows you cannot build libraries like you can in Linux, but you CAN individually call all the functions provided in the repository, so I just replicated the steps taken in the get_hr_net() and validate() functions.

**Comment by eddiesmo** [comment]
@FrancescoPiemontese Hi, I'm trying to run this repository on Windows 10. Can you please elaborate on the process you did to get it to work on Windows?
I don't follow what "individually call all the functions provided in the repository" means in practice.
Thank you!

**Comment by lh5533223** [comment]
> 嗨，我没有遵循任何教程。PyTorch 支持 Windows 10，因此您不需要进行大量修改。我遇到的主要问题是，在 Windows 中，你不能像在 Linux 中那样构建库，但你可以单独调用存储库中提供的所有函数，所以我只是复制了 get_hr_net（） 和 validate（） 函数中采取的步骤。

您好，我也想详细了解一下您在windows下不运行make指令前提下如何执行的train.py和test.py中的代码。非常感谢！
