### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by aliYaHf** [leoxiaobin/deep-high-resolution-net.pytorch#36]
protoc --version
libprotoc 3.4.0
and protobuf versuon is 3.4.0. I would be grateful if someone could provide some help.

**Comment by iFighting** [comment]
how do solve this problem?

**Comment by aliYaHf** [comment]
pip uninstall ptotobuf
pip install -U protobuf
---- 原始邮件 ----
