### ISSUE TITLE
Detection result on COCO test-dev.

### ISSUE THREAD

**Issue by DouYishun** [leoxiaobin/deep-high-resolution-net.pytorch#4]
Can you share the detection result on COCO test-dev2017 which has human AP of 60.9?
For comparison on test-dev.

**Comment by oujieww** [comment]
i also have this problem.

**Comment by KaiserLew** [comment]
Also need this.

**Comment by leoxiaobin** [comment]
You can download them from [OneDrive](https://1drv.ms/f/s!AhIXJn_J-blWzzDXoz5BeFl8sWM-) or [GoogleDrive](https://drive.google.com/drive/folders/1fRUDNUDxe9fjqcRZ2bnF_TKMlO0nB_dk?usp=sharing)

**Comment by mrbulb** [comment]
May I ask which detection model you use so that can achieve the huaman AP of 60.9?

**Comment by zimenglan-sysu-512** [comment]
the same question as @mrbulb

**Comment by lijiannuist** [comment]
Hi @leoxiaobin 
[https://drive.google.com/drive/folders/1Wy5oq9ac1tTgGy67wR1Uu8djSDnf0pOL](url) is 60.9AP for human detection?

**Comment by lijiannuist** [comment]
Hi @leoxiaobin 
What is human detection results of your proposed link. 56.4 AP or 60.9 AP？
