### ISSUE TITLE
CUDA Out of memory during training

### ISSUE THREAD

**Issue by dallas94** [leoxiaobin/deep-high-resolution-net.pytorch#54]
I am training a small dataset using a GTX 1070. I have installed the correct requirements and dependencies and everything seems to run fine on the train.py. The only issue is that the graphics card runs out of memory. This is an 8 gb card.

Besides changing the batch size is there anything that can be done to reduce the memory load?

**Comment by Muhtasham** [comment]
@dallas94 Can you please tell how did you manage to reduce batch size? Thanks

**Comment by Aliiiu** [comment]
pls were u able to resolve this problem? if yes pls share
