### ISSUE TITLE
Do you have plan to do pose estimation by bottom-up way?

### ISSUE THREAD

**Issue by murdockhou** [leoxiaobin/deep-high-resolution-net.pytorch#60]
Hi, thanks for your work. Do you have a plan using bottom-up way to solve human pose estimation question? Maybe its faster than this top-down way (specially for yolov3 + hrnet)?
thanks~

**Comment by leoxiaobin** [comment]
Yes, we have proposed a bottom-up approach based-on HRNet, and we will also release it in the feature. thanks for your attention.

**Comment by murdockhou** [comment]
@leoxiaobin , grateful! Please let me know as soon as possible that you release it, thanks a lot.
