### ISSUE TITLE
What is the usage of half_body_transform?

### ISSUE THREAD

**Issue by xiongzihua** [leoxiaobin/deep-high-resolution-net.pytorch#63]
I find half_body_transform is used in coco dataset, recalculate center and scale according to upper body or lower body.
Can someone tell me why we need to do this, is it an data augmentation trick?

**Comment by leoxiaobin** [comment]
Half body data augmentation is frome http://presentations.cocodataset.org/ECCV18/COCO18-Keypoints-Megvii.pdf. You can get the detail from that.
