### ISSUE TITLE
Model imagenet pretrain scripts

### ISSUE THREAD

**Issue by GongXinyuu** [leoxiaobin/deep-high-resolution-net.pytorch#66]
Hi Leo, thanks for your great work! I'm wondering can you also release the model imagenet pretrain scripts? Thanks!

**Comment by ArchNew** [comment]
You can refer to https://github.com/HRNet/HRNet-Image-Classification, the specific script is under the link: https://github.com/HRNet/HRNet-Image-Classification/tree/master/experiments

**Comment by GongXinyuu** [comment]
Thanks!

**Comment by ArchNew** [comment]
@GongXinyuu I might've pointed you to wrong places. HRNet paper actually gives their training schedule for imagenet pretrain. You can look the paper more closely. The place I pointed you to is for HRNetV2, might not fit for V1
