### ISSUE TITLE
Cant get the 90.3 result on MPII

### ISSUE THREAD

**Issue by HuangChenyang123** [leoxiaobin/deep-high-resolution-net.pytorch#78]
I trained the pose_hrnet_w32 network which input is 256 *192 on MPII, and can only get 90.1 result.

**Comment by dragonfly90** [comment]
@HuangChenyang123, is it because the ankle and knee performing worse?

**Comment by JJBOY** [comment]
hello, the json this project provieded seems modified the scale and center compared with the raw data provieded by mpii. So when we use the test.json convert from h5, we get bad results. Normally, the pckh in test data should be 1%-2% higher than val data, but we get lower results in test data.
Have you got same problem?

**Comment by xuxixia** [comment]
> hello, the json this project provieded seems modified the scale and center compared with the raw data provieded by mpii. So when we use the test.json convert from h5, we get bad results. Normally, the pckh in test data should be 1%-2% higher than val data, but we get lower results in test data.
> Have you got same problem?
Do you solve this? I have the same problem

**Comment by zqylx** [comment]
My result is also 90.1, have you solved this problem?

**Comment by mobeixiaoxin** [comment]
@zqylx ,how many GPUs do you use?

**Comment by mobeixiaoxin** [comment]
@HuangChenyang123 ，my result is also 90.1, have you solved this problem?
thanks!
