### ISSUE TITLE
训练时只用了可见的关键点吗？

### ISSUE THREAD

**Issue by lhh17** [leoxiaobin/deep-high-resolution-net.pytorch#83]
在coco.py中，我发现您是这样设置的：   if t_vis > 1:  t_vis = 1    从后面的代码看，您计算loss的时候只算对可见关键点进行的计算。貌似已标注了的被遮挡的关键点并没做参与到训练中。请问您为什么这样设置？加上被遮挡的关键点训练会导致性能下降吗？

**Comment by ArchNew** [comment]
of course not. You need to read the code more closely. All joints with v=2 are reassigned to t_vis=1, and all joints with v=1 remain t_vis=1. In loss computation, there are only t_vis=1 and t_vis=0. So you tell me, do they consider all occluded but marked joints?

**Comment by lhh17** [comment]
Thanks very much for your answer.
