### ISSUE TITLE
How can I evaluate my model on MPII test set?

### ISSUE THREAD

**Issue by xtyDoge** [leoxiaobin/deep-high-resolution-net.pytorch#85]
How can I test my model on test set and get the output file like `evaluatePCKh.m` on MPII website? Is there any tools for converting test results to .m file?
THX

**Comment by gddingcs** [comment]
Same request here! Any solutions?

**Comment by xtyDoge** [comment]
@gddingcs 
Maybe you can see https://github.com/anibali/eval-mpii-pose, it provides a test.h5 file that contains 11731 individuals. You can convert it to json file and use it to replace test.json to get the pred.mat in dimension of [11731,16,2]. And eval-mpii-pose also provides tools for convert this pred.mat to the format that MPII website required.

**Comment by JJBOY** [comment]
hello, the json this project provieded seems  modified the scale and center compared with the raw data provieded by mpii. So when we use the test.json convert from h5, we get bad results. Normally, the pckh in test data should be 1%-2% higher than  val data, but we get lower results in test data.
Have you got same problem?

**Comment by Marshall0304** [comment]
> hello, the json this project provieded seems modified the scale and center compared with the raw data provieded by mpii. So when we use the test.json convert from h5, we get bad results. Normally, the pckh in test data should be 1%-2% higher than val data, but we get lower results in test data.
> Have you got same problem?

hello, i wonder how long it takes to receive the test result email?
