### ISSUE TITLE
Dose anyone have the right test.json that contains 11731 samples for mpii test set? 

### ISSUE THREAD

**Issue by HuangChenyang123** [leoxiaobin/deep-high-resolution-net.pytorch#99]
Dose anyone have the right test.json that contains 11731 samples? I would appreciate it if you could send it to me. My email address is 464383828@qq.com ,Thank you!

**Comment by cpapaionn** [comment]
Hello, did you find the correct test.json file? If yes, please let me know. My email is cpapaionn@csd.auth.gr. Thank you!
